// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDStAah_wgxHIHj55_zviCRD2j8uUen-7Q',
    appId: '1:667464483623:web:1126829e37e668ff035f02',
    messagingSenderId: '667464483623',
    projectId: 'flutter-c80fa',
    authDomain: 'flutter-c80fa.firebaseapp.com',
    storageBucket: 'flutter-c80fa.firebasestorage.app',
    measurementId: 'G-JGMBN4PF3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4B7R8xBiSoYPT413l50tc1i4SEQFscic',
    appId: '1:667464483623:android:108fa32e8f0f8708035f02',
    messagingSenderId: '667464483623',
    projectId: 'flutter-c80fa',
    storageBucket: 'flutter-c80fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYggbh48DU55XZ-SAlVyjRP3zgbE7VMDU',
    appId: '1:667464483623:ios:5088b84805627296035f02',
    messagingSenderId: '667464483623',
    projectId: 'flutter-c80fa',
    storageBucket: 'flutter-c80fa.firebasestorage.app',
    iosBundleId: 'com.example.gymApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYggbh48DU55XZ-SAlVyjRP3zgbE7VMDU',
    appId: '1:667464483623:ios:5088b84805627296035f02',
    messagingSenderId: '667464483623',
    projectId: 'flutter-c80fa',
    storageBucket: 'flutter-c80fa.firebasestorage.app',
    iosBundleId: 'com.example.gymApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDStAah_wgxHIHj55_zviCRD2j8uUen-7Q',
    appId: '1:667464483623:web:14d4a1abe8d9ddad035f02',
    messagingSenderId: '667464483623',
    projectId: 'flutter-c80fa',
    authDomain: 'flutter-c80fa.firebaseapp.com',
    storageBucket: 'flutter-c80fa.firebasestorage.app',
    measurementId: 'G-P34J21STP5',
  );

}